# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9ac47a8affbf787b0073bf013af0cbe0218dea1170b76c126dc8f2e1c579684b6c77fbde462fee87f76cf5d0a8e2876ba7e03918b5a722cd1b5acfb92b7f634

test:
  secret_key_base: 79c7787f1be96d66baa63822dd9cf451c4df8fe34842290bdfcbaa0528c22e5d015d31b282c1d3528d4abc21a236457c8b81d8b4ab53d4d925bf09d9d939cb13

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
